save_dir: results_large_scale
datasets: ["dota2", "phishing", "optical_radar", "monitor_gas", "covertype"]
methods: ["random", "kmeans++", "fastclara", "kmc2", "onebatch", "kmeans++ls", "banditpam"]
params:
    onebatch:
        batch_size: [100, 300, 500, 1000]
    fastclara:
        n_sampling_iter: [5, 50]
    clara:
        n_sampling_iter: [5, 50]
    kmeans++ls:
        Z: [5, 10]
    kmc2:
        chain_length: [20, 100, 200]
    banditpam:
        max_iter: [0, 2, 5]
K: [10, 50, 100]
N: null
seeds: [0, 1, 2, 3, 4]